version: "3.9"
services:
  stream-by-yuda:
    build: .
    container_name: stream-by-yuda
    env_file:
      - .env
    ports:
      - "${PORT-7575}:7575"
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
    restart: unless-stopped
